#!/usr/bin/env python3
"""Validate release tags and generate checksums plus a binary Homebrew formula."""

import argparse
import hashlib
from pathlib import Path
import re
import tarfile

PLATFORMS = ("darwin-arm64", "darwin-amd64", "linux-arm64", "linux-amd64")
REPOSITORY = "https://github.com/kris-hansen/git-weight"
NUMBER = r"(?:0|[1-9][0-9]*)"
IDENTIFIER = rf"(?:{NUMBER}|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
TAG_PATTERN = re.compile(rf"v({NUMBER}\.{NUMBER}\.{NUMBER}(?:-{IDENTIFIER}(?:\.{IDENTIFIER})*)?)")


def version_for(tag):
    match = TAG_PATTERN.fullmatch(tag)
    if not match:
        raise ValueError("expected vMAJOR.MINOR.PATCH or vMAJOR.MINOR.PATCH-prerelease")
    return match[1]


def package(tag, directory):
    version = version_for(tag)
    checksums = {}
    # Fail closed: a formula must never contain a missing or malformed archive.
    for platform in PLATFORMS:
        name = f"git-weight-{platform}.tar.gz"
        path = directory / name
        with tarfile.open(path, "r:gz") as archive:
            members = archive.getmembers()
            if {m.name for m in members} != {"git-weight", "LICENSE", "README.md"} or len(members) != 3:
                raise ValueError(f"unexpected archive contents: {name}")
            if not all(m.isfile() for m in members):
                raise ValueError(f"archive contains non-regular files: {name}")
            if not archive.getmember("git-weight").mode & 0o111:
                raise ValueError(f"binary is not executable: {name}")
        checksums[name] = hashlib.sha256(path.read_bytes()).hexdigest()

    lines = [
        "# Generated by git-weight's release workflow. Do not edit by hand.",
        "class GitWeight < Formula",
        '  desc "Find what is weighing down your Git repository"',
        f'  homepage "{REPOSITORY}"',
        f'  version "{version}"',
        '  license "MIT"',
        "",
        '  depends_on macos: :sonoma if OS.mac?',
        "",
    ]
    for os_name, platform_os in (("macos", "darwin"), ("linux", "linux")):
        lines.append(f"  on_{os_name} do")
        for arch, platform_arch in (("arm", "arm64"), ("intel", "amd64")):
            name = f"git-weight-{platform_os}-{platform_arch}.tar.gz"
            lines.extend([
                f"    on_{arch} do",
                f'      url "{REPOSITORY}/releases/download/{tag}/{name}"',
                f'      sha256 "{checksums[name]}"',
                "    end",
            ])
        lines.extend(["  end", ""])
    lines.extend([
        "  def install",
        '    bin.install "git-weight"',
        "  end",
        "",
        "  test do",
        '    assert_equal "git-weight #{version}\\n", shell_output("#{bin}/git-weight --version")',
        '    system "git", "init", "-q", "fixture"',
        '    report = JSON.parse(shell_output("#{bin}/git-weight summary --repo fixture --json"))',
        '    assert_equal 0, report.fetch("objects").fetch("blob").fetch("count")',
        "  end",
        "end",
        "",
    ])
    (directory / "git-weight.rb").write_text("\n".join(lines))
    (directory / "checksums.txt").write_text(
        "".join(f"{digest}  {name}\n" for name, digest in sorted(checksums.items()))
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    validate = commands.add_parser("validate")
    validate.add_argument("tag")
    generate = commands.add_parser("package")
    generate.add_argument("tag")
    generate.add_argument("directory", type=Path)
    args = parser.parse_args()
    try:
        version = version_for(args.tag)
        if args.command == "validate":
            print(f"tag={args.tag}\nversion={version}\nprerelease={str('-' in version).lower()}")
        else:
            package(args.tag, args.directory)
    except (ValueError, OSError, tarfile.TarError) as error:
        parser.exit(1, f"release: {error}\n")


if __name__ == "__main__":
    main()
